# Generated by Django 3.0.3 on 2020-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_study', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportModel',
        ),
    ]
