# Generated by Django 3.0.3 on 2020-03-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_study', '0002_delete_sportmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartModel',
        ),
    ]
