# Generated by Django 3.0.3 on 2020-03-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_study', '0003_delete_startmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndModel',
        ),
    ]
